#!/usr/bin/env bash
#
# Copy this file to /etc/libvirt/hooks, make sure it's called "qemu".
# After this file is installed, restart libvirt.
# From now on, you can easily add per-guest qemu hooks.
# Add your hooks in /etc/libvirt/hooks/qemu.d/vm_name/hook_name/state_name.
# For a list of available hooks, please refer to https://www.libvirt.org/hooks.html
#
# --- My edits ---
# v3.0 Added warning about executable files in hook folder
# v2.0 Added Logging feature for hook script. This was missing in the passthrough post qemu file. See: '/var/log/libvirt/custom_hooks.log'
# v1.1: Added Sleep/suspend logic block, for risingprism's 'libvirt-nosleep@' service file. 
#    (NOTE: If using 'isolate' in hook script, exclude nosleep service by adding IgnoreOnIsolate=yes to .service file)
#

GUEST_NAME="$1"
HOOK_NAME="$2"
STATE_NAME="$3"
MISC="${@:4}"

# --- Logging setup ---
LOGFILE="/var/log/libvirt/custom_hooks.log"

log() {
    # timestamp + VM + hook + state + message
    printf '%s [%s] [%s/%s] %s\n' \
        "$(date '+%Y-%m-%d %H:%M:%S')" \
        "$GUEST_NAME" "$HOOK_NAME" "$STATE_NAME" "$*" \
        >> "$LOGFILE"
}

# --- ADDED "SLEEP/SUSPEND" LOGIC: ---
# Manage the "nosleep" service based on VM state
case "$HOOK_NAME" in
    "prepare")
        log "Starting libvirt-nosleep@${GUEST_NAME}.service"
        if ! systemctl start "libvirt-nosleep@${GUEST_NAME}.service" >>"$LOGFILE" 2>&1; then
            log "ERROR: failed to start libvirt-nosleep@${GUEST_NAME}.service"
        fi
        ;;
    "release")
        log "Stopping libvirt-nosleep@${GUEST_NAME}.service"
        if ! systemctl stop "libvirt-nosleep@${GUEST_NAME}.service" >>"$LOGFILE" 2>&1; then
            log "ERROR: failed to stop libvirt-nosleep@${GUEST_NAME}.service"
        fi
        ;;
esac

# --- Original script + logging ---
BASEDIR="$(dirname "$0")"

HOOKPATH="$BASEDIR/qemu.d/$GUEST_NAME/$HOOK_NAME/$STATE_NAME"

# Buffer the entirety of stdin so we can pass it on to other scripts.
STDIN=$(cat)

set -e  # If a script exits with an error, we should as well.

# check if it's a non-empty executable file  
# /!\ WARNING /!\ This tries to run all executable file in the folder  
#     one after the other. (Make sure .bak files are NOT executable.)
if [ -f "$HOOKPATH" ] && [ -s "$HOOKPATH" ] && [ -x "$HOOKPATH" ]; then
    log "Executing hook file: $HOOKPATH"
    # run hook, capturing stdout/stderr into log
    if ! eval "\"$HOOKPATH\"" "$@" <<< "$STDIN" >>"$LOGFILE" 2>&1; then
        # we won't reach here with set -e, but kept for clarity if you disable it
        log "ERROR: hook file failed: $HOOKPATH"
    fi
elif [ -d "$HOOKPATH" ]; then
    log "Executing hook directory: $HOOKPATH"
    while read -r file; do
        # check for null string
        if [ -n "$file" ]; then
            log "Executing hook file in dir: $file"
            if ! eval "\"$file\"" "$@" <<< "$STDIN" >>"$LOGFILE" 2>&1; then
                log "ERROR: hook file in dir failed: $file"
            fi
        fi
    done <<< "$(find -L "$HOOKPATH" -maxdepth 1 -type f -executable -print;)"
else
    log "No hook found at $HOOKPATH"
fi
